name: terraform
on:
  push:
    branches:
      - '**'
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@v1
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: deploy
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform apply
        uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          workspace: ${{ secrets.TF_CLOUD_WORKSPACE }}
          type: apply
          wait-for-completion: true

