name: tflint
on:
  push:
    branches:
      - '**'
  workflow_call:
jobs:
  tflint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v1
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact --minimum-failure-severity=error
